#!/bin/bash

#_PWD=`dirname $0`
#SCRIPT_DIR=`dirname ${_PWD}`
#SYNC_HOME=`dirname ${SCRIPT_DIR}`

SYNC_HOME="/home/bigeagle/mirror"
LOG_URL="/index/mlog/"

waitall() {
	local FAIL=0
	for pid in "$@"; do
		wait $pid || (( FAIL++ ))
	done
	return $FAIL
}


# set_stat $file $item $value
# status file is JSON formated as:
#{
#    'status': 0, //-1 for syncing, 0 for success, other for fail
#    'upstream':'rsync://upstream',
#    'log':'mirror.log'
#}

set_stat()
{
	file=$1
    if [ ! -f $file ];then
        echo "{'discription':'','status':'','upstream':'','lastsync':'','log':''}" > $file
    fi
    item=$2
	value=$3
    json=`perl -pe "s|('$item':).*?,|\1'$value',|" $file`
    echo $json > $file
}

check_dirs()
{
	if [ ! -d $SYNC_HOME ]; then
	  echo "$SYNC_HOME does not exist, please create it, then run this script again."
	  exit 1
	fi

	if [ ! -d $SYNC_LOGS ]; then
		mkdir -p $SYNC_LOGS
	fi

	if [ ! -d "$SYNC_HOME/status" ]; then
		mkdir -p "$SYNC_HOME/status"
	fi
}
