#!/bin/bash

#_PWD=`dirname $0`
#SCRIPT_DIR=`dirname ${_PWD}`
#SYNC_HOME=`dirname ${SCRIPT_DIR}`

SYNC_HOME="/home/bigeagle/mirror"

waitall() {
	local FAIL=0
	for pid in "$@"; do
		wait $pid || (( FAIL++ ))
	done
	return $FAIL
}


# set_stat $file $item $value
# status file is JSON formated as:
#{
#    'status': 0, //-1 for syncing, 0 for success, other for fail
#    'upstream':'rsync://upstream',
#    'log':'mirror.log'
#}

set_stat()
{
	_file=$1
    if [ ! -f $_file ];then
        echo '{"discription":"","status":"","upstream":"","lastsync":"","log":""}' > $_file
    fi
    _item=$2
	_value=$3
	_json=`perl -pe "s|(\"$_item\":).*?([,}])|\1\"$_value\"\2|" $_file`
    echo $_json > $_file
}

get_stat()
{
    _file=$1
    _item=$2
    echo `perl -pe "s/.*?\"$_item\":\"(.*?)\"[,}].*/\1/" $_file`
}

check_dirs()
{
	if [ ! -d $SYNC_HOME ]; then
	  echo "$SYNC_HOME does not exist, please create it, then run this script again."
	  exit 1
	fi

	if [ ! -d $SYNC_LOGS ]; then
		mkdir -p $SYNC_LOGS
	fi

	if [ ! -d "$SYNC_HOME/status" ]; then
		mkdir -p "$SYNC_HOME/status"
	fi
}
